import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="absolute  min-h-[60px] bg-gray-500 flex items-center justify-between w-full gap-10 py-6 px-8">
          <div>
             <Link href='/' className='p-4 bg-green-400 text-gray-700 font-semibold rounded-2xl'>Back To Home</Link>
          </div>
          <div className="flex gap-5">
              {["post", "article", "about"].map((item)=>(
            <Link key={item} href={`/${item}`}>
              <button className="px-8 py-3 text-xl text-gray-700 hover:text-gray-900 bg-slate-200 hover:bg-slate-300 rounded-lg">
                {item}
              </button>
              </Link>
            ))}
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
